/**
 * CogniDocs Configuration
 * Generated by: cognidocs init
 */

export default {
  "entry": "./src",
  "output": "./docs",
  "theme": "gitbook",
  "darkMode": false,
  "frameworks": [
    "react"
  ],
  "exclude": [
    "**/*.test.ts",
    "**/*.test.tsx",
    "**/node_modules/**",
    "**/dist/**"
  ],
  "coverage": {
    "enabled": true,
    "thresholds": {
      "docs": 80,
      "types": 90
    }
  }
};
